version: '2'

services:
  # Service untuk database MongoDB
  item-db:
    # Menggunakan image MongoDB versi 3
    image: mongo:3
    # Menggunakan volume app-db
    volumes:
      - app-db:/data/db
    # Menetapkan kebijakan restart policy
    restart: always

  # Service untuk aplikasi
  item-app:
    # Menggunakan image yang sudah di push ke Docker Hub
    image: robifirmansyah/item-app:v1
    # Mapping port 80 di host ke port 8080
    ports:
      - "80:8080"
    # Memastikan item-app hanya berjalan setelah item-db diluncurkan
    depends_on:
      - item-db
    # Menetapkan kebijakan restart policy
    restart: always

# Volume untuk persistent storage
volumes:
  app-db:
